apiVersion: v1
kind: Service
metadata:
  name: customer-view-service
spec:
  ports:
  - port: 8084
    targetPort: 8084
  type: NodePort
  selector:
    svc: customer-view-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: customer-view-service
  labels:
    application: ftgo
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        svc: customer-view-service
        application: ftgo
    spec:
      containers:
      - name: customer-view-service
        image: customer-view-service:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8084
          name: httpport
        env:
          - name: JAVA_TOOL_OPTIONS
            value: "-Xmx256m"
          - name: JAVA_OPTS
            value: "-Dsun.net.inetaddr.ttl=30"
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://ftgo-mysql/eventuate
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: ftgo-db-secret
                key: username
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ftgo-db-secret
                key: password
          - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
            value: com.mysql.jdbc.Driver
          - name: EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS
            value: ftgo-kafka:9092
          - name: EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING
            value: ftgo-zookeeper:2181
          - name: SPRING_DATA_MONGODB_URI
            value: mongodb://mongodb/bankingexampledb
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8084
          initialDelaySeconds: 20
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8084
          initialDelaySeconds: 20
          periodSeconds: 20
---
